### PR TITLE
Dialoque (Intro)

### PR DESCRIPTION
**Pull request by Byteron**

### CODE REVIEW

**Review by T4g1 — CHANGES_REQUESTED** [review]
Good stuff, i didnot went through the code but still some small remarks:

- I would click to continue the dialog
- Add some animation arrow thing in the bottom right ? (like arrow when theres still dialogs to come and square when its over after that panel)
- The most important remark: Make the background stops UI inputs from reaching the game behind (mouse filter block or something)

**Comment by Byteron** [comment]
> Make the background stops UI inputs from reaching the game behind (mouse filter block or something)

This is already fixed by the UI PR.
It's because the tile highlighter uses _input instead of _unhandled_input.
only _unhandled_input is stopped by UI elements.

I will add the click to continue thing though.

**Comment by Byteron** [comment]
I don't think the arrow button is necessary. Ready to be merged.

**Comment by T4g1** [comment]
Good, note on that change: It was done to fix a bug where PopupLabel prevent building selections. I changed the mouse filters to fix that in UI (was wondering why it was broken again): It should be fine now but so you know. Arrow thing is not mandatory no, ill test it and then we can merge

**Pull request merged**
